# Generated by Django 4.2 on 2024-02-04 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales_rest", "0004_automobilevo_color_automobilevo_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automobilevo",
            name="sold",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="automobilevo",
            name="vin",
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="automobile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automobile_sales",
                to="sales_rest.automobilevo",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_sales",
                to="sales_rest.customer",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="salesperson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesperson_sales",
                to="sales_rest.salesperson",
            ),
        ),
    ]
