# Generated by Django 4.2 on 2024-02-04 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_rest", "0006_alter_sale_automobile_alter_sale_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automobilevo",
            name="import_href",
        ),
    ]
