# Generated by Django 4.2 on 2024-02-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sales_rest", "0007_remove_automobilevo_import_href"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="automobile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="sales_rest.automobilevo",
            ),
        ),
    ]
